apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-delivery-deployment
spec:
  selector:
    matchLabels:
      app: pizza-delivery-service
  template:
    metadata:
      labels:
        app: pizza-delivery-service
        app.kubernetes.io/name: pizza-delivery-service
        app.kubernetes.io/part-of: pizza-delivery-service
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - name: pizza-delivery-service
        image: salaboy/pizza-delivery:1.0.0-agentic-amd64
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: JAVA_OPTS
          value: "-XX:+UseParallelGC -XX:ActiveProcessorCount=1 -XX:MaxRAMPercentage=75 -XX:TieredStopAtLevel=1"   
        - name: PUB_SUB_NAME
          value: pubsub       
        - name: PUB_SUB_TOPIC
          value: topic
        - name: DAPR_HTTP_ENDPOINT
          value: <YOUR_DAPR_HTTP_ENDPOINT_HERE>
        - name: DAPR_GRPC_ENDPOINT
          value: <YOUR_DAPR_HTTP_ENDPOINT_HERE>
        - name: DAPR_API_TOKEN
          value: <YOUR_DAPR_API_TOKEN_HERE>
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pizza-delivery-service
spec:
  selector:
    app: pizza-delivery-service
  ports:
  - port: 80
    targetPort: 8080         