apiVersion: apps/v1
kind: Deployment
metadata:
  name: pizza-delivery-deployment
spec:
  selector:
    matchLabels:
      app: pizza-delivery-service
  template:
    metadata:
      annotations:
        dapr.io/app-id: delivery-service
        dapr.io/app-port: "8080"
        dapr.io/enabled: "true"
        dapr.io/log-level: "debug"
        dapr.io/config: "tracing"
        dapr.io/sidecar-image: kaspernissen/daprd:tracing-v9-linux-arm64-linux-arm64
        dapr.io/env: "OTEL_SERVICE_NAME=delivery-service-daprd"
        instrumentation.opentelemetry.io/inject-java: "opentelemetry/instrumentation"
      labels:
        app: pizza-delivery-service
        app.kubernetes.io/name: pizza-delivery-service
        app.kubernetes.io/part-of: pizza-delivery-service
        app.kubernetes.io/version: 0.1.0
    spec:
      containers:
      - name: pizza-delivery-service
        #image: salaboy/pizza-delivery:1.0.0-agentic-amd64
        #image: salaboy/pizza-delivery:1.0.0-agentic-arm64
        image: kaspernissen/pizza-delivery:1.0.0-agentic-tracing-v8-arm64
        imagePullPolicy: Always
        env:
        - name: SERVER_PORT
          value: "8080"
        - name: PUB_SUB_NAME
          value: pubsub       
        - name: PUB_SUB_TOPIC
          value: topic    
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        ports:
        - containerPort: 8080