apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kvstore
spec:
  type: state.postgresql
  version: v2
  metadata:
  - name: host
    value: "postgresql.default.svc.cluster.local"
  - name: port
    value: "5432"
  - name: database
    value: "dapr"
  - name: user
    value: "postgres"
  - name: password
    value: "postgres"  
  - name: timeout
    value: 10  
  - name: actorStateStore
    value: "true"  
